In [1]:
import numpy as np

In [2]:
arr=np.arange(0,11)

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
arr[5]

5

In [5]:
arr[2:7]

array([2, 3, 4, 5, 6])

In [6]:
arr[:7]

array([0, 1, 2, 3, 4, 5, 6])

In [7]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [8]:
arr[0:5]=20

In [9]:
arr

array([20, 20, 20, 20, 20,  5,  6,  7,  8,  9, 10])

In [12]:
arr=np.arange(0,11)

In [13]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [14]:
arr[:]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [15]:
arr1=arr.copy()

In [16]:
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [17]:
arr1[5:]=10

In [18]:
arr1

array([ 0,  1,  2,  3,  4, 10, 10, 10, 10, 10, 10])

In [21]:
d2=[[1,2,3],[4,5,6],[7,8,9]]
arr2d=np.array(d2)

In [22]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [23]:
arr2d[0]

array([1, 2, 3])

In [24]:
arr2d[0,2]

3

In [25]:
arr2d[:2,:1]

array([[1],
       [4]])

In [26]:
arr2d[:2,1:]

array([[2, 3],
       [5, 6]])

In [28]:
arr2d[0:,:2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [29]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [30]:
arr>5

array([False, False, False, False, False, False,  True,  True,  True,
        True,  True])

In [31]:
arr<12

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

In [32]:
barr=arr<6

In [33]:
barr

array([ True,  True,  True,  True,  True,  True, False, False, False,
       False, False])

In [35]:
arr[barr]

array([0, 1, 2, 3, 4, 5])

In [36]:
arr[arr>7]

array([ 8,  9, 10])

In [37]:
arr[arr<4]

array([0, 1, 2, 3])

In [38]:
arrt=np.arange(30).reshape(5,6)

In [39]:
arrt

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [42]:
arrt[1:3,1:3]

array([[ 7,  8],
       [13, 14]])