In [1]:
my_list=[1,2,3]

In [2]:
my_list

[1, 2, 3]

In [9]:
import numpy as np

In [10]:
arr=np.array(my_list)

In [11]:
arr

array([1, 2, 3])

In [12]:
math=[[1,2,3],[4,5,6],[7,8,9]]
np.array(math)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
np.arange(0,13,2)

array([ 0,  2,  4,  6,  8, 10, 12])

In [16]:
np.zeros(3)

array([0., 0., 0.])

In [17]:
np.zeros((4,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [18]:
np.ones(3)

array([1., 1., 1.])

In [19]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [20]:
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [21]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [22]:
np.random.rand(5)

array([0.22717681, 0.09959675, 0.90677018, 0.88523382, 0.74374304])

In [23]:
np.random.rand(3,3)

array([[0.4963829 , 0.07698305, 0.21609423],
       [0.30939654, 0.40658517, 0.4116611 ],
       [0.32531808, 0.51295009, 0.01613322]])

In [24]:
np.random.randn(5)

array([-0.42037113, -1.35633367, -0.53473227, -1.97078176, -0.86942218])

In [25]:
np.random.randn(3)

array([0.19987189, 0.29907632, 0.27865468])

In [26]:
np.random.randint(0,10)

1

In [27]:
np.random.randint(1,100,20)

array([96, 65, 59, 29, 39, 74, 99, 94, 82, 93, 44, 93, 43, 99, 90, 60,  8,
       24, 71, 33])

In [34]:
arr=np.arange(25)

In [35]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [30]:
rarr=np.random.randint(1,50,10)

In [31]:
rarr

array([43, 26, 45,  4, 14, 18, 10, 12, 35, 22])

In [36]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [37]:
rarr

array([43, 26, 45,  4, 14, 18, 10, 12, 35, 22])

In [38]:
rarr.max()

45

In [39]:
rarr.min()

4

In [40]:
rarr.argmax()

2

In [41]:
rarr.argmin()

3

In [42]:
arr.shape

(25,)

In [43]:
arr=arr.reshape(5,5)

In [44]:
arr.shape

(5, 5)

In [45]:
arr.dtype

dtype('int32')

In [46]:
rarr.dtype

dtype('int32')